language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
  - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
- oraclejdk8
script: mvn install -Popenshift -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  skip_cleanup: true
  provider: openshift
  user: abhilash14300@hotmail.com
  password:
    secure: BEXi1ll4JzF3JYxBp+nINJr3MnzBVt4MRpO4+Em4pLP3yK03LfPS4WKblY/d8uvBqC9WRx1gexcIik+S7RDmPoGDEQ/aBZhzXi6Htkn/CfDnuAWLCJRs1KcruOJLzHnd9Vo74NtiQ/0oTRF8DiHoFpDiOOtMUGty0fjGqSaZWscX4axUE3Qed9jwX72hCYt8B6w+EF9EIGW/BJns6M3o9TDnZ99RcURRVSc6kz2mKKhAT33eUvv+nGFW+aRhj5wQ0B7uPkOy/+EagMmC1lB8btYtRQFPYLTbeHDMx9C/0gy11TepV4Fxhk82uqp7JLZGA3+NFVrT2dTvTW0m+W8FBCLMTMVGkjUFa4HweX/buuwQjh5O4QeF5SKoIsI1GrRl7Gq/ndfuzAJtkZ6ttYRgYlNU5JWxY/4VMEWjsNAZGiPQWaMyqh3nn4T39XEeyKrEaRDr8WXLh3Nqcojty+YbyXiinbOzhF3X7V9oImtWyJPb5Xcxm3uwZTmreanWB0G4G8F4X2zAB2L+zVjFsHUvLuX6WoIZJ8E6ClGyTsO1fNNktLMmnHUgRLrMT1XdwcGdro7owoHYnxVZONCr1eeEc492iscgvotGBRoMchbrFIj6Ip2XaMEYP3GTbg+v0d98cCDm7NuorKBYTj7mlfX4d3P3PQw6l8YwEkQuCwa7iNw=
  app: ashiq
  domain: diviso
  file: /home/travis/build/mohamed-ashiq/test/target/demo-0.0.1-SNAPSHOT.jar
  on:
    repo: mohamed-ashiq/test
