language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
  - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
- oraclejdk8

script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target 58f4562f2d527100cd00004c@ashiq-diviso.rhcloud.com:/var/lib/openshift/58f4562f2d527100cd00004c/app-root/data
  on:
    branch: master

addons:
  ssh_known_hosts: ashiq-diviso.rhcloud.com
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /deploy_rsa
- ssh-add /deploy_rsa
