language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
  - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
- oraclejdk8
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_deploy:
  - git config --global user.email 'mohamed.ashiq@lxisoft.com'
  - git config --global user.name 'mohamed-ashiq'
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://ccf997adbcf66af4af5fa1c005758fc7c33ddc7f@github.com/mohamed-ashiq/test.git --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key: ccf997adbcf66af4af5fa1c005758fc7c33ddc7f
  file:
    - "demo-0.0.1-SNAPSHOT.jar"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/