language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - MAVEN_OPTS="-XX:MaxPermSize=256m -Xmx512m"
  - JAVA_OPTS="-XX:MaxPermSize=256m -Xmx512m"
jdk:
- oraclejdk8
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: releases
  api_key: ccf997adbcf66af4af5fa1c005758fc7c33ddc7f
  file: "target/demo-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: false